version: '3'
services:
  redis:
    image: redis:7.2
    container_name: llm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15
    container_name: llm-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser         # ✅ 사용자명
      POSTGRES_PASSWORD: mypassword # ✅ 비밀번호
      POSTGRES_DB: mydatabase       # ✅ 생성할 DB 이름
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  redis-data:
  postgres-data:

