version: '3'
services:
  redis:
    image: redis:7.2
    container_name: llm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15
    container_name: llm-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser         # ✅ 사용자명
      POSTGRES_PASSWORD: mypassword # ✅ 비밀번호
      POSTGRES_DB: mydatabase       # ✅ 생성할 DB 이름
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: llm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: llm_chat
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
volumes:
  redis-data:
  postgres-data:
  mongo-data:

