version: '3'
services:
  redis:
    image: redis:7.2
    container_name: llm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes

volumes:
  redis-data:

